paths:
  /users:
    post:
      summary: Creates a new user.
      consumes:
      - application/json
      parameters:
      - in: body
        name: user
        description: The user to create.
        schema:
          $ref: '#/definitions/User'
      responses:
        200:
          description: OK
  /users1:
    post:
      summary: Creates a new user.
      consumes:
      - application/json
      parameters:
      - in: body
        name: user
        description: The user to create.
        schema:
          type: object
          required:
          - userName
          properties:
            userName:
              type: string
            firstName:
              type: string
            lastName:
              type: string
      responses:
        201:
          description: Created
definitions:
  User:
    type: object
    required:
    - userName
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string

swagger: '2.0'
tags:
- description: >-
    Testing swagger 2.0 to grpc conversion
  name: test
x-components: {}